# Generated by Django 4.1.4 on 2022-12-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="job_title",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
